image: ruby:2.4.0

pipelines:
  tags:
    '0.1.1':
      - step:
          name: Deploy to Rubygems MRI
          image: ruby:2.5.0
          deployment: production
          script:
            - bash .circleci/setup-rubygems.sh
            - gem build legion-json.gemspec
            - gem push "legion-json-$(git describe --tags).gem"
definitions:
  caches:
    bundler: vendor/bundle
