version: 2 # use CircleCI 2.0
orbs:
  jira: circleci/jira@1.0.2
jobs:
  "rubocop":
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: gem install rubocop
      - run:
          name: Run Rubocop
          command: rubocop
      - store_test_results:
          path: test_results
  "ruby-2.0":
    docker:
      - image: circleci/ruby:2.0
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results
  "ruby-2.1":
    docker:
      - image: circleci/ruby:2.1
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results
  "ruby-2.2":
    docker:
      - image: circleci/ruby:2.2
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results

  "ruby-2.3":
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results

  "ruby-2.4":
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results
  "ruby-2.5":
    docker:
      - image: circleci/ruby:2.5-node
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results
  "ruby-2.6":
    docker:
      - image: circleci/ruby:2.6-node
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results
  "jruby-9.2":
    docker:
      - image: circleci/jruby:9.2
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results

workflows:
  version: 2
  cop_rake_deploy:
    jobs:
      - rubocop
      - ruby-2.2:
          requires:
            - ruby-2.4
          filters:
            branches:
              only: /\bdevelop\b|\bmaster\b/
      - ruby-2.3:
          requires:
            - ruby-2.4
          filters:
            branches:
              only: /\bdevelop\b|\bmaster\b/
      - ruby-2.4:
          requires:
            - rubocop
      - ruby-2.5:
          requires:
            - ruby-2.4
          filters:
            branches:
              only: /\bdevelop\b|\bmaster\b/
      - ruby-2.6:
          requires:
            - ruby-2.4
          filters:
            branches:
              only: /\bdevelop\b|\bmaster\b/
      - jruby-9.2:
          requires:
            - ruby-2.2
            - ruby-2.3
            - ruby-2.4
            - ruby-2.5
            - ruby-2.6