version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  "rubocop":
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
  "ruby-two-five":
    docker:
      - image: cimg/ruby:2.5
    steps:
      - checkout
      - run:
          name: update bundler
          command: gem update bundler
      - ruby/install-deps
      - ruby/rspec-test
  "ruby-two-six":
    docker:
      - image: cimg/ruby:2.6
    steps:
      - checkout
      - run:
          name: update bundler
          command: gem update bundler
      - ruby/install-deps
      - ruby/rspec-test
  "ruby-two-seven":
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
  "jruby92-8jdk":
    docker:
      - image: circleci/jruby:9.2-jdk8
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results
      - sonarcloud/scan
  "jruby92-11jdk":
    docker:
      - image: circleci/jruby:9.2-jre11
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results
      - sonarcloud/scan
  "jruby92-14jdk":
    docker:
      - image: circleci/jruby:9.2-jdk14
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml
          when: always
      - store_test_results:
          path: test-results
      - sonarcloud/scan
  "sonarcloud":
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - run:
          name: Run Rubocop
          command: bundle exec rubocop --format=json --out=rubocop-result.json
      - sonarcloud/scan

workflows:
  version: 2
  rubocop-rspec:
    jobs:
      - rubocop
      - ruby-two-five:
          requires:
            - rubocop
      - ruby-two-six:
          requires:
            - ruby-two-five
      - ruby-two-seven:
          requires:
            - ruby-two-five
      - sonarcloud:
          requires:
            - ruby-two-five
      - jruby92-8jdk:
          requires:
            - ruby-two-seven
            - ruby-two-six
      - jruby92-11jdk:
          requires:
            - jruby92-8jdk
      - jruby92-14jdk:
          requires:
            - jruby92-8jdk